### ISSUE TITLE
[Feature]: Subnet tags

### ISSUE THREAD

**Issue by elebiodaslingshot** [anyscale/terraform-aws-anyscale-cloudfoundation-modules#12]
### What are you looking for?

Support providing subnet tags.

This can give the benefit of obtaining via data source type = private

### Which module(s)?

- [ ] Root Anyscale Module
- [ ] aws-anyscale-efs
- [ ] aws-anyscale-iam
- [ ] aws-anyscale-s3
- [ ] aws-anyscale-s3-policy
- [ ] aws-anyscale-securitygroups
- [x] aws-anyscale-vpc

### Is it blocking work?

no

### Terraform version

1.3.x (Default)

**Comment by brent-anyscale** [comment]
@elebiodaslingshot can you provide some more details about what you're looking for? You can already pass in tags to the VPC sub-module.

Just a reminder that this VPC configuration is a minimal VPC - and if you have customizations for you're own security, you can build you're own VPC outside of this module - and then pass in the VPC.

That being said, if you have some examples, I'm happy adding that as a future update.

**Comment by elebiodaslingshot** [comment]
```hcl
variable "public_subnet_tags" {
  description = <<-EOT
    (Optional)
    A map of tags for the public subnets.
    Duplicate tags found in the "tags" variable will get duplicated on the resource.
    ex:
    ```
    public_subnet_tags= {
      "type" : "public",
    }
    ```
    Default is an empty map.
  EOT
  type        = map(string)
  default     = {}
}

variable "private_subnet_tags" {
  description = <<-EOT
    (Optional)
    A map of tags for the private subnets.
    Duplicate tags found in the "tags" variable will get duplicated on the resource.
    ex:
    ```
    public_subnet_tags= {
      "type" : "private",
    }
    ```
    Default is an empty map.
  EOT
  type        = map(string)
  default     = {}
}
```

**Comment by brent-anyscale** [comment]
I should have this update released today.

**Comment by elebiodaslingshot** [comment]
Do you allow external contributions or only through Issues?

**Comment by brent-anyscale** [comment]
Only through issues for right now.
The additional tags have been added - let me know if you have any additional questions/needs!
