### ISSUE TITLE
[Feature]: Output Route table ID's

### ISSUE THREAD

**Issue by elebiodaslingshot** [anyscale/terraform-aws-anyscale-cloudfoundation-modules#15]
### What are you looking for?

provide an output for both public and private route tables id's in the root module, which should be able to just use the aws-anyscale-vpc outputs.

### Which module(s)?

- [X] Root Anyscale Module
- [ ] aws-anyscale-efs
- [ ] aws-anyscale-iam
- [ ] aws-anyscale-s3
- [ ] aws-anyscale-s3-policy
- [ ] aws-anyscale-securitygroups
- [] aws-anyscale-vpc

### Is it blocking work?

yes

### Terraform version

1.3.x (Default)

**Comment by brent-anyscale** [comment]
@elebiodaslingshot I understand that you're currently blocked by this - have you tried using:
https://registry.terraform.io/providers/hashicorp/aws/3.5.0/docs/data-sources/route_tables

This will provide you a workaround and unblock you.

**Comment by elebiodaslingshot** [comment]
verified output is working
