### ISSUE TITLE
[bug]: Duplicate VPC Endpoint created in certain situations

### ISSUE THREAD

**Issue by mohamed-liveeo** [anyscale/terraform-aws-anyscale-cloudfoundation-modules#3]
### Current Behavior

Duplicate vpc endpoint [route table association ](https://github.com/anyscale/terraform-aws-anyscale-cloudfoundation-modules/blob/main/modules/aws-anyscale-vpc/vpc-endpoints.tf#L35) due to the duplicate entries in the [`route_table_associations_list`](https://github.com/anyscale/terraform-aws-anyscale-cloudfoundation-modules/blob/main/modules/aws-anyscale-vpc/vpc-endpoints.tf#L3) local value. The reason for this duplication could be that the [`all_route_table_ids`](https://github.com/anyscale/terraform-aws-anyscale-cloudfoundation-modules/blob/main/modules/aws-anyscale-vpc/main.tf#L50) local value is concatenating the existing route table ids with the private route tables ids (which also contains the existing route table ids)

### Expected Behavior

Only one entry for the `all_route_table_ids` local value for each of the existing route table ids

### Steps to Reproduce

Add the below VPC module inputs to the root `anyscale_cloudfoundation_modules` block:

- existing_vpc_id
- existing_vpc_subnet_ids
- existing_vpc_route_table_ids
- anyscale_gateway_vpc_endpoints

### Which module(s)?

- [ ] Root Anyscale Module
- [ ] aws-anyscale-efs
- [ ] aws-anyscale-iam
- [ ] aws-anyscale-s3
- [ ] aws-anyscale-s3-policy
- [ ] aws-anyscale-securitygroups
- [X] aws-anyscale-vpc

### Anyscale Terraform Module version

v0.2.x (Default)

### Terraform version

1.3.x (Default)

### Is it blocking work?

no

**Comment by brent-anyscale** [comment]
This should be resolved. Feel free to re-open if you find that it still happens.
