### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by mohamed-liveeo** [anyscale/terraform-aws-anyscale-cloudfoundation-modules#7]
### Current Behavior

EFS is not automatically mounted after activating a workspace also manual mounting is denied

### Expected Behavior

EFS to be mounted on node when activating a workspace or when manually mounted

### Steps to Reproduce

Activate a workspace in a cloud with the `attach_policy` input is true for the "anyscale-efs" module so the EFS is created with a denied non SecureTransport policy attached

### Which module(s)?

- [ ] Root Anyscale Module
- [X] aws-anyscale-efs
- [ ] aws-anyscale-iam
- [ ] aws-anyscale-s3
- [ ] aws-anyscale-s3-policy
- [ ] aws-anyscale-securitygroups
- [ ] aws-anyscale-vpc

### Anyscale Terraform Module version

v0.2.x (Default)

### Terraform version

1.3.x (Default)

### Is it blocking work?

no

### Additional Information

Removing the attached EFS policy (or changing the policy to allow non SecureTransport connection), the problem is solved and EFS mount is working as intended

**Comment by brent-anyscale** [comment]
Release 0.5.2 should resolve this issue. 
Working internally to identify if we should switch from using NFS for mounting to using the AWS efs mount helper which enabled TLS support for NFS mounts.
